import 'dart:io';
import 'dart:math';

import 'package:flutter/services.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;

import '../models/template_model.dart';
import '../models/variable_model.dart';
import '../models/scheduled_notification.dart';
import 'storage_service.dart';

// Notification channel constants
const _kChannelId = 'noti_sim_channel';
const _kChannelName = 'Notificaciones programadas';
const _kChannelDesc = 'Canal de notificaciones simuladas';

// Small icon must be a monochrome drawable compiled into the APK.
// @drawable/app_icon is generated by flutter_local_notifications default setup.
const _kSmallIcon = '@mipmap/ic_launcher';

class NotificationService {
  static final _plugin = FlutterLocalNotificationsPlugin();

  /// Must be called from main() after timezone initialization.
  static Future<void> init() async {
    const androidSettings = AndroidInitializationSettings(_kSmallIcon);
    const initSettings = InitializationSettings(android: androidSettings);
    await _plugin.initialize(initSettings);

    // Create the notification channel with max importance so heads-up is requested.
    const channel = AndroidNotificationChannel(
      _kChannelId,
      _kChannelName,
      description: _kChannelDesc,
      importance: Importance.max,
      enableVibration: true,
      playSound: true,
    );
    await _plugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);
  }

  // ── Permission helpers ────────────────────────────────────────────────────

  static Future<bool> requestNotificationPermission() async {
    final android = _plugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>();
    if (android == null) return false;
    final granted = await android.requestNotificationsPermission();
    return granted ?? false;
  }

  static const _nativeChannel = MethodChannel('noti_sim/miui');

  /// Opens the system "Alarms & reminders" screen so the user can grant the
  /// exact-alarm permission. Uses the native intent (reliable across OEMs).
  static Future<bool> requestExactAlarmPermission() async {
    if (!Platform.isAndroid) return false;
    try {
      return await _nativeChannel.invokeMethod<bool>('openExactAlarmSettings') ??
          false;
    } catch (_) {
      // Fallback to the plugin's own request flow.
      final android = _plugin
          .resolvePlatformSpecificImplementation<
              AndroidFlutterLocalNotificationsPlugin>();
      if (android == null) return false;
      return await android.requestExactAlarmsPermission() ?? false;
    }
  }

  static Future<bool> areNotificationsEnabled() async {
    final android = _plugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>();
    if (android == null) return false;
    return await android.areNotificationsEnabled() ?? false;
  }

  /// Non-intrusive STATUS check via native AlarmManager.canScheduleExactAlarms().
  /// This is the source of truth: if it returns false, any exactAllowWhileIdle
  /// alarm is silently downgraded to inexact and deferred (fires late / on wake).
  static Future<bool> canScheduleExactAlarms() async {
    if (!Platform.isAndroid) return true;
    try {
      return await _nativeChannel.invokeMethod<bool>('canScheduleExactAlarms') ??
          true;
    } catch (_) {
      return true;
    }
  }

  /// Whether the app is whitelisted from battery optimization. If false, the OS
  /// may force-stop the app and cancel its pending alarms.
  static Future<bool> isIgnoringBatteryOptimizations() async {
    if (!Platform.isAndroid) return true;
    try {
      return await _nativeChannel
              .invokeMethod<bool>('isIgnoringBatteryOptimizations') ??
          true;
    } catch (_) {
      return true;
    }
  }

  /// Opens the battery-optimization whitelist prompt for this app.
  static Future<bool> requestIgnoreBatteryOptimizations() async {
    if (!Platform.isAndroid) return false;
    try {
      return await _nativeChannel.invokeMethod<bool>('openBatteryOptimization') ??
          false;
    } catch (_) {
      return false;
    }
  }

  // ── Core notification builder ─────────────────────────────────────────────

  /// Resolves {variable} placeholders in [text] using the provided variable list.
  /// Values are generated NOW (freeze semantics: value fixed at schedule time).
  static String resolvePlaceholders(
    String text,
    List<VariableModel> variables,
    Map<String, String> overrides,
  ) {
    var result = text;
    for (final v in variables) {
      final key = '{${v.name}}';
      if (result.contains(key)) {
        result = result.replaceAll(key, overrides[v.name] ?? v.generate());
      }
    }
    return result;
  }

  /// Builds the AndroidNotificationDetails for a template.
  static AndroidNotificationDetails _buildAndroidDetails(
    TemplateModel tpl,
    String resolvedBody,
  ) {
    // largeIcon: color icon (FilePathAndroidBitmap) — visible on the right
    final AndroidBitmap<Object>? largeIcon = tpl.largeIconPath != null &&
            File(tpl.largeIconPath!).existsSync()
        ? FilePathAndroidBitmap(tpl.largeIconPath!)
        : null;

    // bigPicture: expanded image style (BigPictureStyleInformation)
    StyleInformation? style;
    if (tpl.bigPicturePath != null &&
        File(tpl.bigPicturePath!).existsSync()) {
      style = BigPictureStyleInformation(
        FilePathAndroidBitmap(tpl.bigPicturePath!),
        largeIcon: largeIcon,
        contentTitle: tpl.appNameLabel,    // shown as bold title in expanded
        summaryText: resolvedBody,         // shown as summary beneath picture
        hideExpandedLargeIcon: false,
      );
    } else if (resolvedBody.length > 40) {
      style = BigTextStyleInformation(
        resolvedBody,
        contentTitle: tpl.appNameLabel,
        summaryText: tpl.appNameLabel,
      );
    }

    return AndroidNotificationDetails(
      _kChannelId,
      _kChannelName,
      channelDescription: _kChannelDesc,
      importance: Importance.max,
      priority: Priority.high,
      largeIcon: largeIcon,
      styleInformation: style,
      // subText shows under the app name line — used for the "app label"
      subText: tpl.appNameLabel,
      groupKey: 'noti_sim_group',
      autoCancel: false,
      ongoing: false,
    );
  }

  // ── Immediate notification (preview / "Probar") ──────────────────────────

  static Future<ScheduledNotification> showImmediate(
    TemplateModel tpl,
    List<VariableModel> variables,
  ) async {
    final id = StorageService.nextNotifId();
    final vals = _generateValues(tpl.title + tpl.body, variables);
    final resolvedTitle = resolvePlaceholders(tpl.title, variables, vals);
    final resolvedBody = resolvePlaceholders(tpl.body, variables, vals);

    final details = NotificationDetails(
      android: _buildAndroidDetails(tpl, resolvedBody),
    );
    await _plugin.show(id, resolvedTitle, resolvedBody, details);

    final sn = ScheduledNotification(
      notifId: id,
      templateId: tpl.id,
      templateName: tpl.name,
      resolvedTitle: resolvedTitle,
      resolvedBody: resolvedBody,
      scheduledAt: DateTime.now(),
    );
    _persist(sn);
    return sn;
  }

  // ── Scheduled notification (zonedSchedule + exactAllowWhileIdle) ──────────

  static Future<ScheduledNotification> scheduleAt(
    TemplateModel tpl,
    List<VariableModel> variables,
    DateTime localTime,
  ) async {
    final id = StorageService.nextNotifId();
    final vals = _generateValues(tpl.title + tpl.body, variables);
    final resolvedTitle = resolvePlaceholders(tpl.title, variables, vals);
    final resolvedBody = resolvePlaceholders(tpl.body, variables, vals);

    final tzTime = tz.TZDateTime.from(localTime, tz.local);

    final details = NotificationDetails(
      android: _buildAndroidDetails(tpl, resolvedBody),
    );

    // exactAllowWhileIdle: fires even in Doze mode (requires SCHEDULE_EXACT_ALARM).
    await _plugin.zonedSchedule(
      id,
      resolvedTitle,
      resolvedBody,
      tzTime,
      details,
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      // Required by flutter_local_notifications iOS path even when targeting Android.
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
    );

    final sn = ScheduledNotification(
      notifId: id,
      templateId: tpl.id,
      templateName: tpl.name,
      resolvedTitle: resolvedTitle,
      resolvedBody: resolvedBody,
      scheduledAt: localTime,
    );
    _persist(sn);
    return sn;
  }

  // ── Cold-delivery self-test ───────────────────────────────────────────────

  /// Schedules a single test notification [seconds] from now. Designed to be
  /// verified with the app fully CLOSED, to prove cold delivery works on this
  /// device. Returns the exact DateTime it will fire.
  static Future<DateTime> scheduleColdTest({int seconds = 60}) async {
    final id = StorageService.nextNotifId();
    final fireAt = DateTime.now().add(Duration(seconds: seconds));
    final tzTime = tz.TZDateTime.from(fireAt, tz.local);

    const details = NotificationDetails(
      android: AndroidNotificationDetails(
        _kChannelId,
        _kChannelName,
        channelDescription: _kChannelDesc,
        importance: Importance.max,
        priority: Priority.high,
        autoCancel: true,
      ),
    );

    await _plugin.zonedSchedule(
      id,
      '✅ Prueba en frío',
      'Si ves esto con la app CERRADA, la entrega en frío funciona.',
      tzTime,
      details,
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
    );

    final sn = ScheduledNotification(
      notifId: id,
      templateId: '__cold_test__',
      templateName: 'Prueba en frío',
      resolvedTitle: '✅ Prueba en frío',
      resolvedBody: 'Test de entrega con app cerrada',
      scheduledAt: fireAt,
    );
    _persist(sn);
    return fireAt;
  }

  // ── Random burst scheduling ───────────────────────────────────────────────

  /// Schedules [count] notifications randomly distributed within [window].
  /// All alarms are pre-calculated and individually registered NOW so the
  /// app can be closed immediately after. No runtime timer is used.
  static Future<List<ScheduledNotification>> scheduleRandom({
    required TemplateModel tpl,
    required List<VariableModel> variables,
    required DateTime windowStart,
    required DateTime windowEnd,
    required int count,
    Duration minGap = const Duration(seconds: 10),
  }) async {
    assert(count > 0);
    assert(windowEnd.isAfter(windowStart));

    final rng = Random();
    final totalMs = windowEnd.difference(windowStart).inMilliseconds;
    final slots = _distributeRandom(
      count: count,
      totalMs: totalMs,
      minGapMs: minGap.inMilliseconds,
      rng: rng,
    );

    final results = <ScheduledNotification>[];
    for (final offsetMs in slots) {
      final fireAt = windowStart.add(Duration(milliseconds: offsetMs));
      final sn = await scheduleAt(tpl, variables, fireAt);
      results.add(sn);
    }
    results.sort((a, b) => a.scheduledAt.compareTo(b.scheduledAt));
    return results;
  }

  /// Returns [count] sorted offsets (ms from 0) within [totalMs],
  /// with at least [minGapMs] between consecutive slots.
  static List<int> _distributeRandom({
    required int count,
    required int totalMs,
    required int minGapMs,
    required Random rng,
  }) {
    final minRequired = count * minGapMs;
    final usable = totalMs - minRequired;
    if (usable <= 0) {
      // Window too narrow: distribute evenly
      return List.generate(count, (i) => (totalMs * i / count).round());
    }
    final raw = List.generate(count, (_) => rng.nextInt(usable))..sort();
    // Add i * minGapMs spacing to each sorted value
    return List.generate(count, (i) => raw[i] + i * minGapMs);
  }

  // ── Cancel ────────────────────────────────────────────────────────────────

  static Future<void> cancel(int notifId) async {
    await _plugin.cancel(notifId);
    final list = StorageService.loadScheduled();
    final updated = list.map((sn) {
      if (sn.notifId == notifId) return sn.copyWith(cancelled: true);
      return sn;
    }).toList();
    await StorageService.saveScheduled(updated);
  }

  static Future<void> cancelAll() async {
    await _plugin.cancelAll();
    final list = StorageService.loadScheduled();
    final now = DateTime.now();
    final updated = list.map((sn) {
      if (!sn.cancelled && sn.scheduledAt.isAfter(now)) {
        return sn.copyWith(cancelled: true);
      }
      return sn;
    }).toList();
    await StorageService.saveScheduled(updated);
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  /// Pre-generates values for all variables referenced in [combined] text.
  static Map<String, String> _generateValues(
    String combined,
    List<VariableModel> variables,
  ) {
    final vals = <String, String>{};
    for (final v in variables) {
      if (combined.contains('{${v.name}}')) {
        vals[v.name] = v.generate();
      }
    }
    return vals;
  }

  static void _persist(ScheduledNotification sn) {
    final list = StorageService.loadScheduled();
    list.add(sn);
    StorageService.saveScheduled(list);
  }

  /// Reprograms all future non-cancelled notifications after a device reboot.
  /// Call from a BOOT_COMPLETED receiver (via flutter_local_notifications plugin).
  static Future<void> rescheduleAfterBoot(
    List<TemplateModel> templates,
  ) async {
    final list = StorageService.loadScheduled();
    final now = DateTime.now();
    for (final sn in list) {
      if (sn.cancelled || sn.scheduledAt.isBefore(now)) continue;
      final tpl = templates.firstWhere(
        (t) => t.id == sn.templateId,
        orElse: () => TemplateModel(
          id: sn.templateId,
          name: sn.templateName,
          title: sn.resolvedTitle,
          body: sn.resolvedBody,
        ),
      );
      final tzTime = tz.TZDateTime.from(sn.scheduledAt, tz.local);
      final details = NotificationDetails(
        android: _buildAndroidDetails(tpl, sn.resolvedBody),
      );
      await _plugin.zonedSchedule(
        sn.notifId,
        sn.resolvedTitle,
        sn.resolvedBody,
        tzTime,
        details,
        androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
      );
    }
  }
}
